name: multi-job-deployment-workflow
on: push
jobs:
    job1:
        name: check path
        runs-on: ubuntu-latest
        steps:
            - name: getting-code
              uses: actions/checkout@v3
            - name: install-dependancies
              uses: npm ci
    job2:
        needs: job1
        name: linting job
        runs-on: ubuntu-latest
        steps:
          - name: linting
            run: npm run lint
    job3:
        name: testing
        runs-on: ubuntu-latest
        steps:
          - name: testing code
            run: npm test
    job4:
        name: build
        runs-on: ubuntu-latest
        steps:
            - name: deploy-step
              run: npm run build 