name: deployment workflow
on: push
jobs:
    job1:
        name: lint-test-deploy job
        runs-on: ubuntu-latest
        steps:
            - name: getting code
              uses: actions/checkout@v3
            - name: installing dependancies
              run: npm ci
            - name: linting-step
              run: npm run lint
            
            - name: testing code step
              run: npm run test
            
            - name: deploy-step
              run: npm run build 