name: deployment workflow
on: push
jobs:
    job1:
        name: lint-test-deploy job
        runs-on: ubuntu-latest
        steps:
            - name: linting-step
              run: npx eslint src/
            
            - name: testing code step
              run: npm test
            
            - name: deploy-step
              run: npm run build 